Repository RondineleG/OnForkHub, pull requests merged in 2024-11, with the labels that each got.

#36 fix: Fixed error when executing commands from the dotnet tool to restore and install husky, removing the csproj configuration and moving it to the commands and executed in the git checkout.
  src/Shared/OnForkHub.Scripts/GitFlowConfiguration.cs
  src/Shared/OnForkHub.Scripts/HuskyConfiguration.cs
  src/Shared/OnForkHub.Scripts/OnForkHub.Scripts.csproj
  src/Shared/OnForkHub.Scripts/Program.cs
Labels: bug

#38 Apply stylecop code analyzer and centralize stylecop package
  .globalconfig
  CODING_STANDARDS.md
  src/Core/OnForkHub.Application/Dtos/Base/PaginationRequestDto.cs
  src/Core/OnForkHub.Application/Dtos/Category/Request/CategoryUpdateRequestDto.cs
  src/Core/OnForkHub.Application/Dtos/Category/Response/CategoryResponseDto.cs
  src/Core/OnForkHub.Application/OnForkHub.Application.csproj
  src/Core/OnForkHub.Core/Entities/Category.cs
  src/Core/OnForkHub.Core/Entities/User.cs
  src/Core/OnForkHub.Core/Entities/Video.cs
  src/Core/OnForkHub.Core/OnForkHub.Core.csproj
  src/Core/OnForkHub.Core/Validations/ValidationErrorMessage.cs
  src/Core/OnForkHub.Core/Validations/ValidationResult.cs
  src/Core/OnForkHub.Core/Validations/ValidationService.cs
  src/Core/OnForkHub.Core/ValueObjects/Email.cs
  src/Core/OnForkHub.Core/ValueObjects/Url.cs
  src/Persistence/OnForkHub.Persistence/Exceptions/DatabaseOperationException.cs
  src/Persistence/OnForkHub.Persistence/Exceptions/PersistenceExceptionHandler.cs
  src/Persistence/OnForkHub.Persistence/OnForkHub.Persistence.csproj
  src/Persistence/OnForkHub.Persistence/Repositories/CategoryRepository.cs
  src/Presentations/OnForkHub.App/OnForkHub.App.csproj
  src/Presentations/OnForkHub.Web/OnForkHub.Web.csproj
  src/Shared/OnForkHub.Abstractions/OnForkHub.Abstractions.csproj
  src/Shared/OnForkHub.Dependencies/OnForkHub.Dependencies.csproj
  test/Core/OnForkHub.Application.Test/OnForkHub.Application.Test.csproj
  test/Core/OnForkHub.Core.Test/OnForkHub.Core.Test.csproj
  test/Persistence/OnForkHub.Persistence.Test/OnForkHub.Persistence.Test.csproj
  test/Shared/OnForkHub.TestExtensions/OnForkHub.TestExtensions.csproj
Labels: enhancement, quality

#76 Merge feature/ImprovingPullRequestCreation into dev
  src/Shared/OnForkHub.Scripts/Git/GitFlowConfiguration.cs
  src/Shared/OnForkHub.Scripts/Git/GitFlowPullRequestConfiguration.cs
  src/Shared/OnForkHub.Scripts/GlobalUsings.cs
  src/Shared/OnForkHub.Scripts/OnForkHub.Scripts.csproj
  src/Shared/OnForkHub.Scripts/Program.cs
Labels: status:in-review, priority:high, size:large

#77 Merge feature/TestPR52 into dev
  src/Shared/OnForkHub.Scripts/Git/GitFlowPullRequestConfiguration.cs
Labels: status:in-review, priority:high, size:large

#85 Merge feature/AddViteAndNpmConfigurations into dev
  .husky/commit-msg
  src/Presentations/OnForkHub.Web.Components/OnForkHub.Web.Components.csproj
  src/Presentations/OnForkHub.Web/OnForkHub.Web.csproj
  src/Shared/OnForkHub.Scripts/Git/GitFlowConfiguration.cs
Labels: status:in-review, priority:high, size:large

#86 Merge feature/ConfigureMergeBranchs into dev
  .husky/post-checkout
  src/Shared/OnForkHub.Scripts/Git/GitFlowPullRequestConfiguration.cs
  src/Shared/OnForkHub.Scripts/Program.cs
Labels: status:in-review, priority:high, size:large

#91 feat(configuregitcloneandbuildstart): Merge feature/ConfigureGitCLoneAndBuildStart into dev
  src/Persistence/OnForkHub.Persistence/GlobalUsings.cs
  src/Presentations/OnForkHub.Api/Configuration/WebApiConfiguration.cs
  src/Presentations/OnForkHub.Api/Endpoints/Base/BaseEndPoint.cs
  src/Presentations/OnForkHub.Api/Endpoints/V1/Categories/GetAllCategoriesEndpoint.cs
  src/Presentations/OnForkHub.Api/Endpoints/V2/Categories/GetAllCategoriesEndpoint.cs
  src/Presentations/OnForkHub.Api/Extensions/ServiceCollectionExtensions.cs
  src/Presentations/OnForkHub.Api/GlobalUsings.cs
  src/Presentations/OnForkHub.Api/Program.cs
  src/Shared/OnForkHub.Scripts/Enums/ELogLevel.cs
  src/Shared/OnForkHub.Scripts/Git/GitEditorService.cs
  src/Shared/OnForkHub.Scripts/Git/GitFlowConfiguration.cs
  src/Shared/OnForkHub.Scripts/Git/GitFlowPullRequestConfiguration.cs
  src/Shared/OnForkHub.Scripts/Git/GitHubClient.cs
  src/Shared/OnForkHub.Scripts/Git/GitOperationException.cs
  src/Shared/OnForkHub.Scripts/GlobalUsings.cs
  src/Shared/OnForkHub.Scripts/Husky/HuskyConfiguration.cs
  src/Shared/OnForkHub.Scripts/Interfaces/IGitEditorService.cs
  src/Shared/OnForkHub.Scripts/Interfaces/IGitHubClient.cs
  src/Shared/OnForkHub.Scripts/Interfaces/ILogger.cs
  src/Shared/OnForkHub.Scripts/Interfaces/IProcessRunner.cs
  src/Shared/OnForkHub.Scripts/Logger/ConsoleLogger.cs
  src/Shared/OnForkHub.Scripts/Models/PullRequestInfo.cs
  src/Shared/OnForkHub.Scripts/OnForkHub.Scripts.csproj
  src/Shared/OnForkHub.Scripts/ProcessRunner.cs
  src/Shared/OnForkHub.Scripts/Program.cs
  src/Shared/OnForkHub.Scripts/Startup.cs
Labels: status:in-review, priority:high, size:large
