Repository RondineleG/OnForkHub, pull requests merged in 2024-12, with the labels that each got.

#94 feat(setupazurecosmosdb): Merge feature/SetupAzureCosmosDB into dev
  .editorconfig
  .husky/commit-msg
  README.md
  docs/assets/logo.svg
  src/Presentations/OnForkHub.Api/Extensions/ServiceCollectionExtensions.cs
  src/Presentations/OnForkHub.Web.Components/OnForkHub.Web.Components.csproj
  src/Presentations/OnForkHub.Web/OnForkHub.Web.csproj
  src/Shared/OnForkHub.Abstractions/Resources/Core/Entities/VideoResources.en.resx
  src/Shared/OnForkHub.Dependencies/OnForkHub.Dependencies.csproj
  src/Shared/OnForkHub.Scripts/CliHandler.cs
  src/Shared/OnForkHub.Scripts/Git/GitAliasConfiguration.cs
  src/Shared/OnForkHub.Scripts/Git/GitEditorService.cs
  src/Shared/OnForkHub.Scripts/Git/GitFlowConfiguration.cs
  src/Shared/OnForkHub.Scripts/Git/GitFlowPullRequestConfiguration.cs
  src/Shared/OnForkHub.Scripts/Git/GitHubClient.cs
  src/Shared/OnForkHub.Scripts/GlobalUsings.cs
  src/Shared/OnForkHub.Scripts/Husky/HuskyConfiguration.cs
  src/Shared/OnForkHub.Scripts/Interfaces/ICliHandler.cs
  src/Shared/OnForkHub.Scripts/Interfaces/IGitAliasConfiguration.cs
  src/Shared/OnForkHub.Scripts/Interfaces/IGitHubClient.cs
  src/Shared/OnForkHub.Scripts/Interfaces/ILogger.cs
  src/Shared/OnForkHub.Scripts/Interfaces/IPackageInstaller.cs
  src/Shared/OnForkHub.Scripts/Logger/ConsoleLogger.cs
  src/Shared/OnForkHub.Scripts/Models/PackageInfo.cs
  src/Shared/OnForkHub.Scripts/Nuget/DependencyPackageInstaller.cs
  src/Shared/OnForkHub.Scripts/OnForkHub.Scripts.csproj
  src/Shared/OnForkHub.Scripts/ProcessRunner.cs
  src/Shared/OnForkHub.Scripts/Program.cs
  src/Shared/OnForkHub.Scripts/Startup.cs
  test/Core/OnForkHub.Application.Test/OnForkHub.Application.Test.csproj
  test/Core/OnForkHub.Core.Test/OnForkHub.Core.Test.csproj
  test/Persistence/OnForkHub.Persistence.Test/OnForkHub.Persistence.Test.csproj
Labels: status:in-review, priority:high, size:large

#108 🤖 Apply quick-fixes by Qodana
  src/Core/OnForkHub.Application/Services/CategoryService.cs
  src/Core/OnForkHub.Core/ValueObjects/Email.cs
  src/Core/OnForkHub.Core/ValueObjects/Url.cs
  src/Presentations/OnForkHub.Api/Endpoints/V1/Categories/GetAllCategoriesEndpoint.cs
  src/Presentations/OnForkHub.Api/Endpoints/V2/Categories/GetAllCategoriesEndpoint.cs
  src/Presentations/OnForkHub.Api/Program.cs
  src/Presentations/OnForkHub.Web.Components/ConfigureServices.cs
  src/Presentations/OnForkHub.Web.Components/VideoPlayer/Player.razor.cs
  src/Presentations/OnForkHub.Web.Components/VideoPlayer/TorrentPlayer.razor.cs
  src/Presentations/OnForkHub.Web.Components/VideoPlayer/VideoPlayerJsInterop.cs
  src/Presentations/OnForkHub.Web/Pages/Advanced.razor
  src/Presentations/OnForkHub.Web/Pages/Home.razor
  src/Presentations/OnForkHub.Web/Pages/TorrentTest.razor
  src/Presentations/OnForkHub.Web/Program.cs
  src/Presentations/OnForkHub.Web/wwwroot/index.html
  test/Core/OnForkHub.Core.Test/Entities/Base/BaseEntityTest.cs
  test/Core/OnForkHub.Core.Test/Exceptions/DomainExceptionTest.cs
  test/Core/OnForkHub.Core.Test/Validations/ValidationResultText.cs
  test/Shared/OnForkHub.TestExtensions/Assertions/ValidationResultAssertions.cs
Labels: ci-cd, configuration, automation

#116 Fix: devcontainer environment
  .devcontainer/devcontainer_setup.sh
  README.md
Labels: configuration, development-tools

#134 Implemented GitHub Actions PR Notifications to Telegram
  .github/workflows/pr-telegram-notify.yml
  .husky/commit-msg
  .husky/commit-msg-qodana
  .husky/post-checkout
  .husky/pre-commit
  .husky/pre-flow-feature-finish
  .husky/pre-push
Labels: ci-cd, automation

#153 Bugfix/fix notification telegram
  .github/workflows/pr-telegram-notify.yml
Labels: ci-cd, devops
